package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Es un BackboneElement que puede representar persona, localización, helthcareService o dispositivo")
public class Participant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Rol del participante")
	private com.CodeableConcept type;
	@org.kie.api.definition.type.Label("Referencia a: Person, Location/HealthcareService or Device")
	private com.Reference actor;

	@org.kie.api.definition.type.Label(value = "código")
	private java.lang.String status;

	public Participant() {
	}

	public com.CodeableConcept getType() {
		return this.type;
	}

	public void setType(com.CodeableConcept type) {
		this.type = type;
	}

	public com.Reference getActor() {
		return this.actor;
	}

	public void setActor(com.Reference actor) {
		this.actor = actor;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public Participant(com.CodeableConcept type, com.Reference actor,
			java.lang.String status) {
		this.type = type;
		this.actor = actor;
		this.status = status;
	}

}