package com.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Appointment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPOINTMENT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "APPOINTMENT_ID_GENERATOR", sequenceName = "APPOINTMENT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("código del estado")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("descripción")
	private java.lang.String description;

	@org.kie.api.definition.type.Label("fecha inicio")
	private java.util.Date start;

	@org.kie.api.definition.type.Label("comentario")
	private java.lang.String comment;

	@org.kie.api.definition.type.Label("medico para el que se solicita")
	private Participant medico;

	@org.kie.api.definition.type.Label("paciente para el que se solicita")
	private Participant paciente;

	public Appointment() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.util.Date getStart() {
		return this.start;
	}

	public void setStart(java.util.Date start) {
		this.start = start;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public com.healthcare.Participant getMedico() {
		return this.medico;
	}

	public void setMedico(com.healthcare.Participant medico) {
		this.medico = medico;
	}

	public com.healthcare.Participant getPaciente() {
		return this.paciente;
	}

	public void setPaciente(com.healthcare.Participant paciente) {
		this.paciente = paciente;
	}

	public Appointment(java.lang.Long id, java.lang.String status,
			java.lang.String description, java.util.Date start,
			java.lang.String comment, com.healthcare.Participant medico,
			com.healthcare.Participant paciente) {
		this.id = id;
		this.status = status;
		this.description = description;
		this.start = start;
		this.comment = comment;
		this.medico = medico;
		this.paciente = paciente;
	}
}